export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_RESET = "AUTH_LOGIN_RESET";

export const AUTH_LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAILURE = "AUTH_LOGOUT_FAILURE";
export const AUTH_LOGOUT_RESET = "AUTH_LOGOUT_RESET";

export const AUTH_REGISTER_REQUEST = "AUTH_REGISTER_REQUEST";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";
export const AUTH_REGISTER_RESET = "AUTH_REGISTER_RESET";

export const AUTH_UPDATE_SELF_REQUEST = "AUTH_UPDATE_SELF_REQUEST";
export const AUTH_UPDATE_SELF_SUCCESS = "AUTH_UPDATE_SELF_SUCCESS";
export const AUTH_UPDATE_SELF_FAILURE = "AUTH_UPDATE_SELF_FAILURE";
export const AUTH_UPDATE_SELF_RESET = "AUTH_UPDATE_SELF_RESET";

export const AUTH_DELETE_SELF_REQUEST = "AUTH_DELETE_SELF_REQUEST";
export const AUTH_DELETE_SELF_SUCCESS = "AUTH_DELETE_SELF_SUCCESS";
export const AUTH_DELETE_SELF_FAILURE = "AUTH_DELETE_SELF_FAILURE";
export const AUTH_DELETE_SELF_RESET = "AUTH_DELETE_SELF_RESET";

export const AUTH_REQUEST_RESET_REQUEST = "AUTH_REQUEST_RESET_REQUEST";
export const AUTH_REQUEST_RESET_SUCCESS = "AUTH_REQUEST_RESET_SUCCESS";
export const AUTH_REQUEST_RESET_FAILURE = "AUTH_REQUEST_RESET_FAILURE";
export const AUTH_REQUEST_RESET_RESET = "AUTH_REQUEST_RESET_RESET";

export const AUTH_RESET_REQUEST = "AUTH_RESET_REQUEST";
export const AUTH_RESET_SUCCESS = "AUTH_RESET_SUCCESS";
export const AUTH_RESET_FAILURE = "AUTH_RESET_FAILURE";
export const AUTH_RESET_RESET = "AUTH_RESET_RESET";
