export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAILURE = "PRODUCT_ADD_FAILURE";
export const PRODUCT_ADD_RESET = "PRODUCT_ADD_RESET";

export const PRODUCT_ALL_REQUEST = "PRODUCT_ALL_REQUEST";
export const PRODUCT_ALL_SUCCESS = "PRODUCT_ALL_SUCCESS";
export const PRODUCT_ALL_FAILURE = "PRODUCT_ALL_FAILURE";
export const PRODUCT_ALL_RESET = "PRODUCT_ALL_RESET";
